name: hok_survey_kiosk
description: A new Flutter project for the Honor of Kings survey kiosk.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  csv: ^6.0.0
  permission_handler: ^11.3.1
  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/HOK BLUE Background.png
    - assets/HOK BLUE Benefits logo.png
    - assets/HOK BLUE CTA.png
    - assets/HOK BLUE Character.png
    - assets/HOK BLUE Gold logo.png
    - assets/HOK BLUE LEVEL INFINITE & TIMI Logo.png
    - assets/HOK BLUE Sparkle 1.png
    - assets/HOK BLUE Sparkle 2 radial.png
    - assets/qr_code_image.JPEG
